version: '3.8'

services:
  cloud9-frontend:
    build:
      context: ../the-cocacola
      dockerfile: Dockerfile
    container_name: the-cocacola-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
  strapi:
    build:
      context: ../Strapi-CocoCola
      dockerfile: Dockerfile
    container_name: strapi-cocacola
    restart: always
    ports:
      - "1337:1337"
    env_file:
      - ../Strapi-CocoCola/.env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=1337
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-doadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-defaultdb}
    ports:
      - "25060:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups/backup.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
