version: '3.8'

services:
  cloud9-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: the-cocacola-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
  strapi:
    build:
      context: ../Strapi-CocoCola
      dockerfile: Dockerfile
    container_name: strapi-cocacola
    restart: always
    ports:
      - "1337:1337"
    env_file:
      - ../Strapi-CocoCola/.env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=1337
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-doadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-defaultdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups/backup.sql:/docker-entrypoint-initdb.d/init.sql

  cloud9-scraper:
    build:
      context: ../cloud9_inventory
      dockerfile: Dockerfile
    container_name: cloud9-scraper-service
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/scraper-finished  # Optional default webhook
    volumes:
      - ../cloud9_inventory/output:/app/output

volumes:
  postgres_data:

